### ISSUE TITLE
ee()->TMPL->log_item() causing exception

### ISSUE THREAD

**Issue by emrysr** [croxton/Stash#154]
Hi,

Not sure if this an issue with your addon or with solspace's user addon..?

_I'm using EE 3.5.4, Solspace User 4.0.9 and Stash 3.0.5_

I've had to comment out line 537 in ext.stash.php in v3.0.5:-

> 537:

      ee()->TMPL->log_item("Stash: batch processing queued queries");

The exception stops solspace's user plugin from sending out user invite emails ( tag:{exp:user:key} ).

Is the _ee()->TMPL->log_item()_ required? it seems to work fine without it?

Here's a screenshot of the exception shown:
![user-vs-stash-addon-exception](https://cloud.githubusercontent.com/assets/1466013/24496545/71bc3244-1530-11e7-81d6-47d5c2eb820d.png)

I've not added an issue here before... please delete this if it's not relevant.

PS. Love this plugin.. I couldn't work without it. Thank you for your awesome addon 👍

**Comment by croxton** [comment]
Dupe of #137

This is (apparently) fixed in the latest version of Solspace User. Can you verify?

**Comment by emrysr** [comment]
I've already got 4.0.9 - only just updated. I'll keep an eye out for future updates. Thanks.

**Comment by mrpatricko** [comment]
Can confirm that this issue is still occurring with EE 6.1.5, Stash 3.1.0, and User 5.4.0.

**Comment by mrpatricko** [comment]
User 5.4.1 was recently released and it addresses this issue. ( Thank you, Robin! :) )

"Changed a library call name to increase compatibility with the Stash add-on."

https://eeharbor.com/user/changelog
